name: Build extension

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml

  build:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install tools
        run: npm i

      - name: Publish
        run: npm run publish
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.platform.llvm }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
